// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }

//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   // 🔥 WEB CONFIG (مهم جدًا)
//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'YOUR_WEB_API_KEY',
//     appId: 'YOUR_WEB_APP_ID',
//     messagingSenderId: '193428326730',
//     projectId: 'noon-clone-85e4a',
//     authDomain: 'noon-clone-85e4a.firebaseapp.com',
//     storageBucket: 'noon-clone-85e4a.firebasestorage.app',
//   );

//   // 🔥 ANDROID CONFIG
//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyD88d9dyX4UEIgjVYoFYr4Q29lk6HZdkIE',
//     appId: '1:193428326730:android:f0a7ef67ec63be4c6999b3',
//     messagingSenderId: '193428326730',
//     projectId: 'noon-clone-85e4a',
//     storageBucket: 'noon-clone-85e4a.firebasestorage.app',
//   );

//   // 🔥 iOS CONFIG
//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyDn1A7RUNWlQu2dfd4HYddsO18cGz7RQEQ',
//     appId: '1:193428326730:ios:b8a97f8dd6dfb0916999b3',
//     messagingSenderId: '193428326730',
//     projectId: 'noon-clone-85e4a',
//     storageBucket: 'noon-clone-85e4a.firebasestorage.app',
//     iosBundleId: 'com.example.noonClone',
//   );
// }